blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://developers.applovin.com/en/max/flutter/overview/integration
    about: Documentation for the AppLovin MAX Flutter Plugin
  - name: Support
    url: https://developers.applovin.com
    about: Answers to common questions and support for AppLovin MAX
