blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://support.axon.ai/en/max/flutter/overview/integration
    about: Documentation for the AppLovin MAX Flutter Plugin
  - name: Support
    url: https://support.axon.ai/en/max/faq/common-questions-from-publishers
    about: Answers to common questions and support for AppLovin MAX
